### ISSUE TITLE
Dynamic versioning with setuptools_scm

### ISSUE THREAD

**Issue by ns-rse** [cgat-developers/cgat-apps#137]
Can use [setuptools_scm](https://github.com/pypa/setuptools-scm) to dynamically set the version which is derived from Git tags.

Necessary lines in `pyproject.toml`

```toml
[build-system]
requires = [
  ...
  "setuptools[toml]>=8"
]

[project]
...
dynamic = ["version"]

[tool.setuptools_scm]
write_to = "isoslam/_version.py"
```

Optional addition if using `pytest-cov` to report test coverage.

```
[tool.coverage.run]
omit = [
  "isoslam/_version.py"
]
```

Can then import the version in `__init__.py` to make it available.

```python
from importlib.metadata import version

release = version("<pkgname>")
__version__ = ".".join(release.split("."[:2]))
```
